import * as path from "path";
import { LatexLengthCustomSettings } from "../../shared/latex-length/LatexLengthSettings";
import { SourceFile } from "./SourceFile";

export type CodeMappingID = number;

// The context of a code mapping is the value of certain "things"
// in the LaTeX engine at the beginning of mapped code extract
// (e.g. the value of a length macro such as \linewidth)
export interface CodeMappingContext {
    // The values of variable length units and length macros are given in points (pt)
    readonly variableLengthUnitValues: Record<string, number>;
    readonly lengthMacrosValues: Record<string, number>;

    // The list of paths used by the graphicx package to search for images
    readonly graphicsPaths: string[];
}

export class MissingMappingFieldError {}

export class CodeMapping {
    readonly type: string;
    readonly sourceFile: SourceFile;
    readonly lineNumber: number;
    readonly id: CodeMappingID;

    readonly context: CodeMappingContext;

    private constructor(
        type: string,
        sourceFile: SourceFile,
        lineNumber: number,
        id: number,
        context: CodeMappingContext
    ) {
        this.type = type;
        this.sourceFile = sourceFile;
        this.lineNumber = lineNumber;
        this.id = id;
        this.context = context;
    }

    get contextualLatexLengthSettings(): LatexLengthCustomSettings {
        return {
            variableUnitsValues: this.context.variableLengthUnitValues,
            lengthMacroValues: this.context.lengthMacrosValues
        };
    }

    static fromLatexGeneratedMapping(
        mappingAsString: string,
        mainSourceFileDirectoryPath: string,
        sourceFiles: SourceFile[]
    ): CodeMapping {
        const mappingEntries = mappingAsString
            .split("\n")
            .map(singleLine => {
                const firstSpaceIndex = singleLine.indexOf(" ");
                return {
                    key: singleLine.substring(0, firstSpaceIndex),
                    value: singleLine.substring(firstSpaceIndex + 1),
                };
            });

        function getEntryValueOrFail(key: string): string {
            const entry = mappingEntries.find(entry => entry.key === key);
            if (!entry) {
                console.error(`No mapping entry "${key}" could be found in the given entry.`);
                throw new MissingMappingFieldError();
            }

            return entry.value;
        }

        // Paths generated by LaTeX can sometimes be relative
        // and/or contain '.' directories, useless successive slashes, etc.
        // We therefore transform the path to ensure all source files
        // are created using a normalised, absolute path.
        const pathEntry = getEntryValueOrFail("path");
        const normalisedAbsolutePath = path.isAbsolute(pathEntry)
                                     ? path.normalize(pathEntry)
                                     : path.join(
                                           mainSourceFileDirectoryPath,
                                           path.normalize(pathEntry)
                                       );

        function getAllLengthValuesWithPrefix(prefix: string, newKeyPrefix: string = ""): Record<string, number> {
            return Object.fromEntries(
                mappingEntries
                    .filter(entry => entry.key.startsWith(prefix))
                    .map(entry => [
                        entry.key.replace(prefix, newKeyPrefix),
                        parseFloat(entry.value)
                    ])
            );
        }

        // We extract various contextual entries to build a context object
        const context = {
            variableLengthUnitValues: getAllLengthValuesWithPrefix("length_unit_"),
            lengthMacrosValues: getAllLengthValuesWithPrefix("length_macro_", "\\"),

            // Multiple graphics paths are specified by enclosing them
            // in successive curly-braces blocks (with no other separator).
            // We split the paths to make a list out of them
            // and make sure to remove all the curly braces from the blocks.
            graphicsPaths: getEntryValueOrFail("graphicspath")
                .split(/\}\s*\{/)
                .map(dirtyPath => dirtyPath.replace(/^\{|\}$/g, ""))
        };

        const sourceFile = sourceFiles.find(sourceFile =>
            sourceFile.absolutePath === normalisedAbsolutePath
        ) ?? new SourceFile(normalisedAbsolutePath);

        return new CodeMapping(
            getEntryValueOrFail("type"),
            sourceFile,
            parseInt(getEntryValueOrFail("line")),
            parseInt(getEntryValueOrFail("id")),
            context
        );
    }
}